import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./produk/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "testing-next-js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Suspense  fallback={< Loading />}>{children}

      </Suspense>
      </body>
      
    </html>
  );
}
